name: URL Shortening Service CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  WORKING_DIR: url-shortening-service
  KEYGEN_SERVICE_DIR: keygen-service
  NODE_VERSION: 24.6


jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json

      - name: Install Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: npm ci

      - name: Run Linter
        working-directory: ${{ env.WORKING_DIR }}
        run: lerna run lint

  test:
    runs-on: ubuntu-24.04

    services:
      app-db:
        image: mongodb/mongodb-community-server:6.0-ubi8
        ports:
          - "27017:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: pass

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json

      - name: Start Local Keygen Service
        run: docker compose up -d keygen-service-local

      - name: Install Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: npm ci

      - name: Run Tests
        working-directory: ${{ env.WORKING_DIR }}
        env:
          MONGODB_SERVER: mongodb://root:pass@localhost:27017
          MONGODB_DB: testing
          KEYGEN_SERVICE_URL: localhost:8080
          JWT_SECRET: ${{ secrets.JwtSecret }}
          BASE_REDIRECTION_URL: https://testing.run
        run: lerna run test

  pages-build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json

      - name: Install Dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: npm ci

      - name: Run Build
        working-directory: ${{ env.WORKING_DIR }}
        env:
          VITE_API_URL: http://localhost:3000
          VITE_SETTINGS_REQUEST_URL: https://github.com/petersonddb/url-shortening/issues/new
        run: lerna run --scope url-shortening-pages build

  service-build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ vars.DockerRegistry }}/url-shortening/service

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DockerUsername }}
          password: ${{ secrets.DockerPassword }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          provenance: true
          sbom: true
